name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Updates every hour
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_traffic: yes
          base_repository: yes
          repositories_forks: yes
          config_timezone: Asia/Dhaka
          repository: Akib-Osmani/data-science-journey


